---
defaultDatabase: "test1"
logLevel: null
logFile: null
databases:
- id: "test1"
  host: "localhost"
  port: "7687"
  user: null
  password: null
  path: ""
  options: null
- id: "test2"
  host: null
  port: 0
  user: null
  password: null
  path: "/tmp/bionetdb-test2"
  options: null